### ISSUE TITLE
Grpc862 in goker failed to repro

### ISSUE THREAD

**Issue by Mskxn** [timmyyuan/gobench#14]
https://github.com/timmyyuan/gobench/blob/5affb0a20384fcce37d3527262be0477b294372f/gobench/goker/blocking/grpc/862/grpc862_test.go#L57-L60
It seems that G2 will not hang up forever when timeout at L58. 
I failed to repro it using goleak with a little delay before leak check instead of check it immediately.

**Comment by timmyyuan** [comment]
This is possible because `goleak` filters goroutines by checking whether they are in a blocked state. In the case of 862, the goroutine switches between being blocked and running within a loop.
