### ISSUE TITLE
Potential new initroduced bug in cockroach1055&cockroach1462

### ISSUE THREAD

**Issue by Jay-deng** [timmyyuan/gobench#7]
I found out that goker might have introduced a new bug when reproducing cockroach1055 ([https://github.com/timmyyuan/gobench/blob/master/gobench/goker/blocking/cockroach/1055/cockroach1055_test.go.](url))
When the program is executed according to the path s.StartTask -> s.Quiesce -> s.Stop, for the variable s.drain, the lack of s.drain.Done() will also cause the program to block.

**Comment by timmyyuan** [comment]
Could you reproduce this new bug? If so, I think we can post the backtrace of the new bug on cockroach1055

**Comment by Jay-deng** [comment]
This bug is hard to reproduce  in the original test file, but I've extracted the variable of _s.drain_ related code, you can check the code in go playground [here](https://go.dev/play/p/OaNV32a5DHZ). 

Here is the backtrace information in my IDE:
![image](https://user-images.githubusercontent.com/37053493/227124082-93e637dc-2ae4-491a-96e7-8e44c7c280e4.png)

**Comment by timmyyuan** [comment]
Thank you for pointing this out. I took a closer look and found that in the [original code snippet](https://github.com/cockroachdb/cockroach/pull/1055/files), there was no explicit call for FinishTask (which actually called s.drain.Done()). That's why there’s more bugs. Great job!

**Comment by Jay-deng** [comment]
Yes, and I also find due to this reason, there is another blocking bug related to condition variables in cockroach#1462. Since _p.cond.Wait()_ is called in the test functioni, the corresponding _p.cond.Broadcast()_ are not called for no call for FinishTask().  
You can also check this in [cockroach#1462](https://github.com/timmyyuan/gobench/tree/master/gobench/goker/blocking/cockroach/1462). 

Anyway, thanks for your reply~
