### ISSUE TITLE
more data races in etcd#8194

### ISSUE THREAD

**Issue by yanke-xu** [timmyyuan/gobench#8]
As described in backtrace, there are two operations (one is write and the other one is read) can cause a data race. However, because the Goroutine 9 and Goroutine 10 are called in parallel，we cannot determine the execution status of them. 

Case 1:
```
Write by goroutine 9:
      command-line-arguments.testLessorRenewExtendPileup()
            /root/gobench/goker/nonblocking/etcd/8194/etcd8194_test.go:14
Read by goroutine 10:
      command-line-arguments.(*lessor).runLoop()
            /root/gobench/goker/nonblocking/etcd/8194/etcd8194_test.go:36
```

Case 2:
```
Write by goroutine 9:
      command-line-arguments.testLessorRenewExtendPileup()
            /root/gobench/goker/nonblocking/etcd/8194/etcd8194_test.go:13
Read by goroutine 10:
      command-line-arguments.(*lessor).runLoop()
            /root/gobench/goker/nonblocking/etcd/8194/etcd8194_test.go:35
```

Case 3:
```
Write by goroutine 9:
      command-line-arguments.testLessorRenewExtendPileup()
            /root/gobench/goker/nonblocking/etcd/8194/etcd8194_test.go:13
Read by goroutine 10:
      command-line-arguments.(*lessor).runLoop()
            /root/gobench/goker/nonblocking/etcd/8194/etcd8194_test.go:36
```

That's to say, case 1-3 can also cause a data race respectively bacause of the concurrency between the two goroutines. When using Go's official data race detector, the bug that is triggered first will be detected and printed, but it cannot be denied that the other three cases are still potential data races.

**Comment by timmyyuan** [comment]
Yes, you are right. If the first data race is triggered, the subsequent programs may be in incorrect states (including data races you mentioned above). Thanks for pointing that out.

**Comment by yanke-xu** [comment]
> Yes, you are right. If the first data race is triggered, the subsequent programs may be in incorrect states (including data races you mentioned above). Thanks for pointing that out.

Thanks for your reply.
